import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next (and git-ignored); its triple-slash
    // reference trips @typescript-eslint/triple-slash-reference.
    ignores: ["node_modules/**", ".next/**", "out/**", "coverage/**", "drizzle/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
